#ifndef __ELEGOO_MOVE_COMMAND_H__
#define __ELEGOO_MOVE_COMMAND_H__

enum ElegooMoveCommand
{
	UNKNOWN_CMD, MOVE_FORWARDS, TURN_RIGHT, HALF_RIGHT, TURN_LEFT, HALF_LEFT, MOVE_BACKWARDS, STOP_MOVING
};

#endif
